version: '3'
services:
  mongo:
    image: mongo:latest
    env_file:
      - .env
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
  api:
    build: .
    ports:
      - '4000:4000'
    volumes:
      - .:/app
    depends_on:
      - mongo
