name: CI Pipeline

on:
  pull_request:
    branches:
      - development

jobs:
  combined-checks:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/datc-base-env:latest
      # Add volume mount for npm cache
      options: --user root -v /home/runner/.npm:/.npm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache npm packages
        uses: actions/cache@v3
        with:
          path: /.npm # Changed to match the volume mount
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install packages
        run: |
          # Ensure cache directory has correct permissions
          mkdir -p /.npm
          chown -R $(id -u):$(id -g) /.npm
          npm install

      # Rest of your steps remain the same
      - name: Frontend Admin Checks
        run: make ci-combined-app-frontend-admin

      - name: Frontend UI Checks
        run: make ci-combined-app-frontend-ui

      - name: Library Components Checks
        run: make ci-combined-lib-components

      - name: Library Theme Checks
        run: make ci-combined-lib-theme
