name: CI Pipeline

on:
  pull_request:
    branches:
      - development

jobs:
  setup:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/datc-base-env:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install packages with caching
        run: |
          echo "Setting up npm cache..."
          npm config set cache /github/home/.npm --global
          npm ci --prefer-offline

  frontend-admin:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/datc-base-env:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install packages
        run: npm ci
      - name: Run Checks
        run: make ci-combined-app-frontend-admin

  frontend-ui:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/datc-base-env:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install packages
        run: npm ci
      - name: Run Checks
        run: make ci-combined-app-frontend-ui

  lib-components:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/datc-base-env:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install packages
        run: npm ci
      - name: Run Checks
        run: make ci-combined-lib-components

  lib-theme:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/datc-base-env:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install packages
        run: npm ci
      - name: Run Checks
        run: make ci-combined-lib-theme
